# fly.toml app configuration file generated for motorhomebot on 2025-08-03T23:13:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'motorhomebot'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  TZ = 'Europe/Madrid'

[processes]
  bot = 'python -m motorhomebot.main'

[[mounts]]
  source = 'data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = false
  ports = []
  processes = ['bot']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
