# fly.toml app configuration file for motorhomebot

app = 'motorhomebot'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  TZ = 'Europe/Madrid'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']  # <-- Cambia a ['bot'] si tu comando de proceso es 'bot'
  [services.ports]
    port = 8080

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
