# fly.toml – motorhomebot (sin webserver)

app = "motorhomebot"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  TZ = "Europe/Madrid"

# Volumen persistente para SQLite
[[mounts]]
  source      = "data"
  destination = "/data"

# Arranque del bot (usa el CMD del Dockerfile o este proceso)
[processes]
  app = "python run.py"

[[vm]]
  memory   = "256mb"
  cpu_kind = "shared"
  cpus     = 1
